### ISSUE TITLE
Sample animation breaks off in the middle

### ISSUE THREAD

**Issue by Dimous** [HaxePunk/SpinePunk#4]
Hello!
I compiled sample with openfl and nme for windows target in release mode (no errors were reported) and both versions have the same issue:

![948wtdjhy1](https://user-images.githubusercontent.com/283939/36350044-048a50a0-14dc-11e8-897d-593ca07a247c.gif)
[As HTML5 video](http://recordit.co/948wtdJHY1)

I played the animation in Spine Skeleton Viewer.

Windows 10 x64
Haxe Compiler 4.0.0 (git build development @ 42fc22254)

haxelib list
```
HaxePunk: 4.0.1 [git]
hxcpp: [git]
lime: [6.2.0]
nme-dev: [5.5.1]
nme-toolkit: [6.2.0]
nme: [6.0.58]
openfl: [7.1.2]
spinehaxe: [git]
SpinePunk: [git]
```

**Comment by bendmorris** [comment]
I'm not able to repro this. Can you confirm the commits your spinehaxe and SpinePunk repos are on?

**Comment by Dimous** [comment]
Today I updated all dependencies and it's working fine. Thanks for attention! Sorry for disturbance.
